<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0.3 (Python 3.9.5 on win32)" generated="20210607 14:12:41.002" rpa="false" schemaversion="2">
<suite id="s1" name="TC1" source="C:\Users\LQA\PycharmProjects\pythonProject\Testcases\TC1.robot">
<test id="s1-t1" name="OpenApp">
<kw name="Open Application" library="AppiumLibrary">
<arg>http://localhost:4723/wd/hub</arg>
<arg>platformName=ANDROID</arg>
<arg>platformVersion=9</arg>
<arg>deviceName=emulator-5554</arg>
<arg>appPackage=com.google.android.calculator</arg>
<arg>appActivity=com.android.calculator2.Calculator</arg>
<arg>automationName=UIAutomator2</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |</doc>
<msg timestamp="20210607 14:12:41.308" level="TRACE">Arguments: [ 'http://localhost:4723/wd/hub' | platformName='ANDROID' | platformVersion='9' | deviceName='emulator-5554' | appPackage='com.google.android.calculator' | appActivity='com.android.calculator2.Calculator' | automationName='UIAutomator2' ]</msg>
<msg timestamp="20210607 14:12:43.352" level="DEBUG">POST http://127.0.0.1:4723/wd/hub/session {"capabilities": {"firstMatch": [{"platformName": "ANDROID", "appium:platformVersion": "9", "appium:deviceName": "emulator-5554", "appium:appPackage": "com.google.android.calculator", "appium:appActivity": "com.android.calculator2.Calculator", "appium:automationName": "UIAutomator2"}]}, "desiredCapabilities": {"platformName": "ANDROID", "platformVersion": "9", "deviceName": "emulator-5554", "appPackage": "com.google.android.calculator", "appActivity": "com.android.calculator2.Calculator", "automationName": "UIAutomator2"}}</msg>
<msg timestamp="20210607 14:12:43.423" level="DEBUG">Starting new HTTP connection (1): 127.0.0.1:4723</msg>
<msg timestamp="20210607 14:12:52.548" level="DEBUG">http://127.0.0.1:4723 "POST /wd/hub/session HTTP/1.1" 500 1251</msg>
<msg timestamp="20210607 14:12:52.548" level="DEBUG">Finished Request</msg>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20210607 14:12:52.549" level="TRACE">Arguments: [  ]</msg>
<msg timestamp="20210607 14:12:52.551" level="FAIL">No application is open</msg>
<msg timestamp="20210607 14:12:52.552" level="DEBUG">Traceback (most recent call last):
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\AppiumLibrary\keywords\keywordgroup.py", line 21, in _run_on_failure_decorator
    raise err
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\AppiumLibrary\keywords\keywordgroup.py", line 16, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\AppiumLibrary\keywords\_screenshot.py", line 31, in capture_page_screenshot
    if hasattr(self._current_application(), 'get_screenshot_as_file'):
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\AppiumLibrary\keywords\_applicationmanagement.py", line 349, in _current_application
    raise RuntimeError('No application is open')</msg>
<status status="FAIL" starttime="20210607 14:12:52.548" endtime="20210607 14:12:52.552"/>
</kw>
<msg timestamp="20210607 14:12:52.553" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20210607 14:12:52.557" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\LQA\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: Command 'C:\Program Files\Java\jdk1.8.0_291\bin\bin\java.exe' not found. Is it installed?
</msg>
<msg timestamp="20210607 14:12:52.557" level="DEBUG">Traceback (most recent call last):
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\AppiumLibrary\keywords\keywordgroup.py", line 21, in _run_on_failure_decorator
    raise err
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\AppiumLibrary\keywords\keywordgroup.py", line 16, in _run_on_failure_decorator
    return method(*args, **kwargs)
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\AppiumLibrary\keywords\_applicationmanagement.py", line 52, in open_application
    application = webdriver.Remote(str(remote_url), desired_caps)
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\appium\webdriver\webdriver.py", line 155, in __init__
    super().__init__(
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\appium\webdriver\webdriver.py", line 225, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, parameters)
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "c:\users\lqa\pycharmprojects\pythonproject\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)</msg>
<status status="FAIL" starttime="20210607 14:12:41.308" endtime="20210607 14:12:52.557"/>
</kw>
<status status="FAIL" starttime="20210607 14:12:41.307" endtime="20210607 14:12:52.557">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Cannot verify the signature of 'C:\Users\LQA\AppData\Local\Programs\Appium\resources\app\node_modules\appium\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v4.17.4.apk'. Original error: Command 'C:\Program Files\Java\jdk1.8.0_291\bin\bin\java.exe' not found. Is it installed?
</status>
</test>
<status status="FAIL" starttime="20210607 14:12:41.004" endtime="20210607 14:12:52.571"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="TC1">TC1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210607 14:12:52.553" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
